# NekoMatch 配置文件
# 使用 Velocity (VC) 作为代理

# 服务器地址配置
# 格式: 服务器名: "IP地址:端口"
servers:
  # 4v4 服务器
  ba1:
    address: "127.0.0.1:1000"

  # 1v1 服务器
  ba2:
    address: "127.0.0.1:5000"

  # 全新玩法
  new1:
    address: "127.0.0.1:6000"

# 游戏模式配置
# 每个模式可以配置多个服务器，插件会自动选择状态为"等待中"的服务器
modes:
  4v4:
    servers:
      - ba1
    description: "四人团队战"

  1v1:
    servers:
      - ba2
    description: "单人对决"

  全新玩法:
    servers:
      - new1
    description: "探索全新游戏模式"
